kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-appgogs
  namespace: gogs-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem