kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-backup
  namespace: gogs-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem