kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-data
  namespace: gogs-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem