apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-monkey-ws
spec:
  workspaces:
    - name: pipeline-ws1
  resources:
  - name: source
    type: git
  - name: image
    type: image
  tasks:
  - name: hello-world
    taskRef:
      name: echo-hello-world
  - name: monkey-build-task
    taskRef:
      name: monkey-build-task
    runAfter: 
      - hello-world
 ################### Workspace Definition ##########
    workspaces:
    - name: src
      workspace: pipeline-ws1
 ################### Workspace Definition Ends #####

    resources:
      inputs:
      - name: source
        resource: source
      outputs:
      - name: image
        resource: image
  - name: hello-person
    taskRef:
      name: echo-hello-person
    runAfter: 
      - monkey-build-task
